# LIST OF REQUIRED PACKAGES -----------------------------------------------
# devtools::install_github("hrbrmstr/nominatim")
# devtools::install_github("hrbrmstr/streamgraph")



library(AMR)
library(data.table)
library(DT)
library(ggridges)
library(ggplot2)
library(inlmisc)
library(lubridate)
library(leaflet)
library(leaflet.extras)
library(plotly)
library(qicharts2)
library(rintrojs)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(sp)
library(survival)
library(ggpubr)
library(survminer)
library(tidyverse)
library(viridis)
library(zoo)
library(jsonlite)
library(nominatim)
library(tidygeocoder)
library(osmdata)
library(sf)
library(geojsonio)
library(cld2)
library(magrittr)
library(htmlwidgets)
library(htmltools)
library(franc)
library(cbsodataR)
library(shinythemes)
library(readr)
library(dodgr)
library(shinyMatrix)
library(streamgraph)




